# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Gitea paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_gid }}"
  with_items:
    - "{{ gitea_base_path }}"
    - "{{ gitea_data_dir_path }}"
    - "{{ gitea_config_dir_path }}"

- name: Ensure Gitea support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ gitea_base_path }}/{{ item }}"
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure Gitea container image is pulled
  community.docker.docker_image:
    name: "{{ gitea_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ gitea_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else gitea_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Gitea container network is created
  community.general.docker_network:
    name: "{{ gitea_container_network }}"
    driver: bridge

- name: Ensure Gitea systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/gitea.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ gitea_identifier }}.service"
    mode: "0640"
